local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>aa", function() mark.add_file() end)
vim.keymap.set("n", "<leader>al", function() ui.toggle_quick_menu() end)
vim.keymap.set("n", "<leader>ap", function() ui.nav_prev() end)
vim.keymap.set("n", "<leader>an", function() ui.nav_next() end)
vim.keymap.set("n", "<leader>a1", function() ui.nav_file(1) end)
vim.keymap.set("n", "<leader>a2", function() ui.nav_file(2) end)
vim.keymap.set("n", "<leader>a3", function() ui.nav_file(3) end)
vim.keymap.set("n", "<leader>a4", function() ui.nav_file(4) end)
vim.keymap.set("n", "<leader>a5", function() ui.nav_file(5) end)
